In [2]:
import numpy as np

In [4]:
a = np.array([np.arange(5, 10), np.arange(12, 17)])
a.shape

(2, 5)

In [11]:
b = np.array([23.2, 25, 22])
b.reshape(3, 1)

array([[23.2],
       [25. ],
       [22. ]])

In [8]:
print(f"dimentions of a : {a.ndim} | dimentions of b : {b.ndim}")

dimentions of a : 2 | dimentions of b : 1


In [9]:
print(f"size of a : {a.size} | size of b : {b.size}")

size of a : 10 | size of b : 3


In [12]:
print(f"type of a : {a.dtype} | type of b : {b.dtype}")

type of a : int64 | type of b : float64


In [15]:
c = np.arange(15)
print(c.shape, c.ndim, c.size, c.dtype)

(15,) 1 15 int64


In [16]:
c = c.reshape(3, 5)
print(c.shape, c.ndim, c.size, c.dtype)

(3, 5) 2 15 int64


In [17]:
d = np.zeros((5, 6))
d

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
e = np.ones((5, 3))
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
a = np.array([np.arange(8, 16, +2), np.arange(22, 30, +2), np.arange(50, 58, +2)])
b = np.array([np.arange(25, 33, +2), np.arange(35, 55, +5), np.arange(4)])

a.shape, b.shape

((3, 4), (3, 4))

In [23]:
print(a)
print("------------------------")
print(b)

[[ 8 10 12 14]
 [22 24 26 28]
 [50 52 54 56]]
------------------------
[[25 27 29 31]
 [35 40 45 50]
 [ 0  1  2  3]]


In [ ]:
print(a <= b)

[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]


In [31]:
print(b ** a)

[[        152587890625      205891132094649   353814783205469041
    627428198704704065]
 [  665298106895417433                    0 -5460838222306938295
   4414812766615896064]
 [                   0                    1    18014398509481984
    639558602475808609]]


In [34]:
c = np.array([3])

print(a % c)

[[2 1 0 2]
 [1 0 2 1]
 [2 1 0 2]]


In [41]:
print(a.all(), a.any(), b.all(), b.any())

True True False True


In [45]:
print(np.tan(a))

[[-6.79971146  0.64836083 -0.63585993  7.24460662]
 [ 0.00885166 -2.1348967   1.17875355 -0.2814296 ]
 [-0.27190061 -6.05327238  0.6738001  -0.61127369]]


In [46]:
a

array([[ 8, 10, 12, 14],
       [22, 24, 26, 28],
       [50, 52, 54, 56]])

In [57]:
a[a%4==0]

array([ 8, 12, 24, 28, 52, 56])

In [52]:
a[2][2:]

array([54, 56])

In [54]:
f = np.arange(20)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
f[3:15:+3]

array([ 3,  6,  9, 12])

In [56]:
f[f%3==0]

array([ 0,  3,  6,  9, 12, 15, 18])

In [59]:
print(np.sum(a), np.max(a), np.min(a))

356 56 8


In [66]:
a = np.array([np.arange(10, 15), np.arange(8, 3, -1), np.arange(-5, -10, -1)])
a

array([[10, 11, 12, 13, 14],
       [ 8,  7,  6,  5,  4],
       [-5, -6, -7, -8, -9]])

In [65]:
np.sort(a)

array([[10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8],
       [-9, -8, -7, -6, -5]])

In [3]:
a = np.random.randint([[10, 150], [200, 5000]], [[100, 300], [700, 15000]], size=(2, 2))
a

array([[  19,  267],
       [ 464, 8634]], dtype=int32)

In [4]:
b = np.random.uniform([[1.2, 2.5], [-12, 3.3]], [[1.5, 5.5], [-11, 3.4]], size=(2, 2))
b

array([[  1.26401263,   3.91245302],
       [-11.79838234,   3.35216676]])

In [8]:
c = np.random.rand(5, 6)
c

array([[0.47634468, 0.33346519, 0.48399524, 0.59102539, 0.77101451,
        0.15107503],
       [0.34311378, 0.32265308, 0.84384097, 0.92134382, 0.75491219,
        0.60898976],
       [0.60701629, 0.55438348, 0.90314572, 0.23096283, 0.24834755,
        0.41755687],
       [0.40703365, 0.49877256, 0.75843234, 0.74202408, 0.62612486,
        0.6880198 ],
       [0.45092698, 0.22384293, 0.51555066, 0.84068093, 0.54689707,
        0.27480832]])

In [9]:
d = np.random.randn(5, 6)
d

array([[ 1.21489166,  0.69218096,  0.95531998, -1.35394018, -1.10384198,
        -0.35900527],
       [ 1.47911338,  0.40308996,  0.73068198, -0.07560355, -0.85124233,
        -0.31858355],
       [-0.07332923, -1.22207412, -0.65278618,  1.00963315,  0.0420377 ,
        -0.10653563],
       [ 0.17348858, -1.11292286,  0.57757973, -0.41707044,  0.92961099,
        -0.44157694],
       [ 0.58829654,  0.13769906, -0.01734482, -0.49061743,  0.8764138 ,
         0.28919498]])

In [7]:
e = np.random.random(size=(3, 5))
e

array([[0.72281894, 0.45731993, 0.77783402, 0.0219033 , 0.40746868],
       [0.81174747, 0.43776739, 0.50569758, 0.26214587, 0.95404357],
       [0.32287929, 0.82715487, 0.10920526, 0.13440634, 0.25209106]])

In [72]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

c = np.vstack((a, b))
c

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [77]:
d = np.vstack((c, np.array([25, 6, 8, 22])))
d

array([[ 2,  4,  6,  8],
       [ 1,  3,  5,  7],
       [25,  6,  8, 22]])

In [80]:
e = np.hstack((a, b))
e

array([2, 4, 6, 8, 1, 3, 5, 7])

In [81]:
mean_a = np.mean(a)
std_a = np.std(a)
norm_a = (a - mean_a) / std_a

norm_a

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [82]:
print(np.mean(norm_a), np.std(norm_a))

0.0 1.0


In [2]:
np.random.seed(50)
a = np.random.randn(6, 8)
a

array([[-1.56035211, -0.0309776 , -0.62092842, -1.46458049,  1.41194612,
        -0.47673214, -0.78046921,  1.07026774],
       [-1.2822926 , -1.3274789 ,  0.12633764,  0.86219372,  0.69673696,
        -0.33456518, -0.99752606,  1.59890829],
       [ 3.31407535,  0.98777046,  0.12386626,  0.74278539, -0.39395585,
         0.14811582, -0.41223445, -0.16071506],
       [ 0.13953147,  0.28546937, -0.28126199,  1.71090732, -0.14976664,
         0.69030672,  1.09520951,  1.3384087 ],
       [-1.36898167,  0.48642763,  0.75352168,  0.36346459, -0.31471048,
         1.37328117, -0.62441716,  0.375754  ],
       [-0.20041632,  0.74303806,  0.85736196, -1.50618929, -1.66635217,
        -0.2189948 , -0.35885843,  0.37852769]])