In [1]:
import numpy as np

In [4]:
a = np.array([np.arange(5, 10), np.arange(12, 17)])
a.shape

(2, 5)

In [11]:
b = np.array([23.2, 25, 22])
b.reshape(3, 1)

array([[23.2],
       [25. ],
       [22. ]])

In [8]:
print(f"dimentions of a : {a.ndim} | dimentions of b : {b.ndim}")

dimentions of a : 2 | dimentions of b : 1


In [9]:
print(f"size of a : {a.size} | size of b : {b.size}")

size of a : 10 | size of b : 3


In [12]:
print(f"type of a : {a.dtype} | type of b : {b.dtype}")

type of a : int64 | type of b : float64


In [15]:
c = np.arange(15)
print(c.shape, c.ndim, c.size, c.dtype)

(15,) 1 15 int64


In [16]:
c = c.reshape(3, 5)
print(c.shape, c.ndim, c.size, c.dtype)

(3, 5) 2 15 int64


In [17]:
d = np.zeros((5, 6))
d

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
e = np.ones((5, 3))
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
a = np.array([np.arange(8, 16, +2), np.arange(22, 30, +2), np.arange(50, 58, +2)])
b = np.array([np.arange(25, 33, +2), np.arange(35, 55, +5), np.arange(4)])

a.shape, b.shape

((3, 4), (3, 4))

In [23]:
print(a)
print("------------------------")
print(b)

[[ 8 10 12 14]
 [22 24 26 28]
 [50 52 54 56]]
------------------------
[[25 27 29 31]
 [35 40 45 50]
 [ 0  1  2  3]]


In [ ]:
print(a <= b)

[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]


In [31]:
print(b ** a)

[[        152587890625      205891132094649   353814783205469041
    627428198704704065]
 [  665298106895417433                    0 -5460838222306938295
   4414812766615896064]
 [                   0                    1    18014398509481984
    639558602475808609]]


In [34]:
c = np.array([3])

print(a % c)

[[2 1 0 2]
 [1 0 2 1]
 [2 1 0 2]]


In [41]:
print(a.all(), a.any(), b.all(), b.any())

True True False True


In [45]:
print(np.tan(a))

[[-6.79971146  0.64836083 -0.63585993  7.24460662]
 [ 0.00885166 -2.1348967   1.17875355 -0.2814296 ]
 [-0.27190061 -6.05327238  0.6738001  -0.61127369]]


In [46]:
a

array([[ 8, 10, 12, 14],
       [22, 24, 26, 28],
       [50, 52, 54, 56]])

In [57]:
a[a%4==0]

array([ 8, 12, 24, 28, 52, 56])

In [52]:
a[2][2:]

array([54, 56])

In [54]:
f = np.arange(20)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
f[3:15:+3]

array([ 3,  6,  9, 12])

In [56]:
f[f%3==0]

array([ 0,  3,  6,  9, 12, 15, 18])

In [59]:
print(np.sum(a), np.max(a), np.min(a))

356 56 8


In [66]:
a = np.array([np.arange(10, 15), np.arange(8, 3, -1), np.arange(-5, -10, -1)])
a

array([[10, 11, 12, 13, 14],
       [ 8,  7,  6,  5,  4],
       [-5, -6, -7, -8, -9]])

In [65]:
np.sort(a)

array([[10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8],
       [-9, -8, -7, -6, -5]])

In [67]:
a = np.random.randint(10, 1000, (5, 6))
a

array([[ 45, 983, 794, 845, 661, 679],
       [698, 608, 795, 125, 742, 669],
       [ 17, 137, 357, 493, 403, 786],
       [264, 830, 594, 846, 524, 804],
       [961,  97, 834, 858, 383, 180]], dtype=int32)

In [68]:
b = np.random.uniform(30, 51, (5, 6))
b

array([[39.15370556, 33.50976384, 43.36346783, 40.32422084, 48.26821204,
        43.29738207],
       [43.08738416, 44.61252225, 41.57656888, 38.41707933, 49.03644515,
        50.30326089],
       [42.53505757, 47.9516776 , 40.9413416 , 49.46438392, 48.78129251,
        44.57444568],
       [31.42603461, 46.37740234, 46.49256576, 46.94231974, 30.03504064,
        46.06399446],
       [40.43711762, 38.23762428, 44.73773961, 40.22570829, 43.15987453,
        49.01379693]])

In [70]:
c = np.random.rand(5, 6)
c

array([[0.90510109, 0.02724067, 0.56254528, 0.07577479, 0.56144537,
        0.61263065],
       [0.82343288, 0.01929412, 0.38969668, 0.81095103, 0.91737402,
        0.9511629 ],
       [0.16900637, 0.42440662, 0.93438735, 0.92877542, 0.46666678,
        0.96146047],
       [0.77780935, 0.21679184, 0.69233285, 0.21589515, 0.61091148,
        0.96294447],
       [0.882896  , 0.82930231, 0.96732858, 0.68226481, 0.88229412,
        0.65293086]])

In [71]:
d = np.random.randn(5, 6)
d

array([[-0.24567214, -0.84930531,  1.33386378,  0.53108623,  0.72155277,
        -0.09429174],
       [ 0.06678324,  0.24945397,  0.2285281 ,  1.04251085, -0.42180004,
        -1.5889296 ],
       [ 0.37441462,  0.38193399, -1.04786259, -0.33077845,  0.20398986,
         0.15903329],
       [ 1.42391505, -0.30977932,  0.28618011,  2.60568291,  0.03423685,
         1.01521599],
       [-0.2856799 , -0.8717855 ,  0.51478393,  0.05239498,  0.91893031,
         0.14287781]])

In [72]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

c = np.vstack((a, b))
c

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [77]:
d = np.vstack((c, np.array([25, 6, 8, 22])))
d

array([[ 2,  4,  6,  8],
       [ 1,  3,  5,  7],
       [25,  6,  8, 22]])

In [80]:
e = np.hstack((a, b))
e

array([2, 4, 6, 8, 1, 3, 5, 7])

In [81]:
mean_a = np.mean(a)
std_a = np.std(a)
norm_a = (a - mean_a) / std_a

norm_a

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [82]:
print(np.mean(norm_a), np.std(norm_a))

0.0 1.0


In [2]:
np.random.seed(50)
a = np.random.randn(6, 8)
a

array([[-1.56035211, -0.0309776 , -0.62092842, -1.46458049,  1.41194612,
        -0.47673214, -0.78046921,  1.07026774],
       [-1.2822926 , -1.3274789 ,  0.12633764,  0.86219372,  0.69673696,
        -0.33456518, -0.99752606,  1.59890829],
       [ 3.31407535,  0.98777046,  0.12386626,  0.74278539, -0.39395585,
         0.14811582, -0.41223445, -0.16071506],
       [ 0.13953147,  0.28546937, -0.28126199,  1.71090732, -0.14976664,
         0.69030672,  1.09520951,  1.3384087 ],
       [-1.36898167,  0.48642763,  0.75352168,  0.36346459, -0.31471048,
         1.37328117, -0.62441716,  0.375754  ],
       [-0.20041632,  0.74303806,  0.85736196, -1.50618929, -1.66635217,
        -0.2189948 , -0.35885843,  0.37852769]])